import $ from 'jquery';
import 'babel-polyfill';
import selectbox from '../blocks/selectbox/selectbox';
import docCards from '../components/doc-cards/docСards';
import aboutBudgetPreparation from '../components/depfin_about_budget_preparation/depfin_about_budget_preparation';
import mediaMain from '../components/media-main/mediaMain';
import main from '../components/main/main';
import tabs from '../blocks/tabs/tabs';
import question from '../blocks/question/question';
import questions from '../components/questions/questions';
import lkNav from '../blocks/lk-nav/lkNav';
import regions from '../components/regions/regions';
import searchForm from '../components/searchForm/searchForm';
import sources from '../components/budget_moscow_sources/budget_moscow_sources';
import govProgram from '../components/services_gov_program/services_gov_program';
import analyticsMain from '../components/depfin-analytics-main/depfin-analytics-main';
import budgetCalcPage from '../pages/depfin_services_budget_calc/depfin_services_budget_calc';
import legend from '../blocks/legend/legend';
import budgetCalcApp from '../components/budget-calc-app/budget-calc-app';
import newsFilter from '../components/news/newsFilter';
import range from '../blocks/range/range';
import dragscroll from '../blocks/drag-scroll/drag-scroll'; // функция, позволяющая сделать любой блок скроллящимся через перетаскивание (добавить класс .js-drag-scroll-element)
import openCon from '../components/open-con/openCon';
import contest from '../components/contest/contest';
import mediaMaterials from '../components/depfin-budget-moscow-media-materials/mediaMaterials';
import openSlider from '../components/open-slider/openSlider';
import govDebt from '../components/gov-debt/govDebt';
import profileEdit from '../components/profile-edit/profileEdit';
import budgetaryPolicy from '../components/budgetary-policy/budgetaryPolicy';
import documentsform from '../components/documents/documents';
import pageHeader from '../components/page-header/pageHeader';
import modal from '../blocks/modal/modal';
import budget_moscow_gov_program from '../components/budget_moscow_gov_program/budget_moscow_gov_program';
import analitycGraphics from '../components/analityc-graphics/analityc-graphics'
import reset from '../components/reset/reset';
import profile from '../components/profile/profile';
import basic_budget_figures from '../components/basic_budget_figures/basic_budget_figures';
import menu from '../blocks/menu/menu'; // главное меню в навбаре
import searchNavbar from '../blocks/search-navbar/search-navbar'; // форма поиска в навбаре
import widgetCard from '../components/widget-card/widgetCard';
import header from '../components/header/header'; // навбар
import toppanel from '../blocks/toppanel/toppanel'; // верхняя панель, общая для сайтов Москвы
import tooltips from '../blocks/tooltip-icon/tooltip-icon'; // тултипы в калькуляторе бюджета
import search from '../components/search/search';
import news_one from '../components/news-one/news-one';
import analitycWidgethead from '../components/analityc-widgethead/analityc-widgethead';
import aboutBudget from '../components/depfin-about-budget/aboutBudget';
import openReit from '../components/depfin-budget-moscow-open-reit/openReit';
import depfinServices from '../components/depfin-services-main/depfin-services-main';
import dropdown from '../blocks/dropdown-block/dropdown';
import openFile from '../components/open-file/open-file';
import rangeUi from '../blocks/range-ui/range-ui';
import contestPopup from '../components/contest-popup/contestPopup';
import socialService from '../components/depfin-services-social-support/depfin-services-social-support.js';
import aip from '../components/budget_aip/budget_aip';
import classifyNew from '../components/classify-new/classifyNew';
import servicesVMO from '../components/depfin_services_VMO/depfin_services_VMO';
import socialSignificant from '../components/services_social_significant/socialSignificant';
import servicesNet from '../components/services_net/servicesNet';
import dropTable from '../blocks/drop-table/dropTable';
import slideArrows from '../blocks/slide-arrows/slideArrows';
import budgetForecast from '../components/budget-forecast/budgetForecast';
import servicesMoscow from '../components/services_moscow/servicesMoscow';
import bluedropdown from '../blocks/blue-dropdown/blue-dropdown';
import documentsCards from '../components/documents-cards/documentsCards';
import tablesActive from '../blocks/table1/table1';
import mrelations from '../components/mrelations/mrelations';
import budgetIncome from '../components/budget_income/budgetIncome';
import budgetExpenses from '../components/budget_expenses/budgetExpenses';
import table from '../blocks/table/table';
import budgetMoscowOpen from '../components/depfin-budget-moscow-open/budgetMoscowOpen';
import buttonsSet from '../blocks/buttons-set/buttonsSet';
import analyticsGovDebt from '../components/analytics-gov-debt/analyticsGovDebt';
import depfin_analytics_income from '../components/depfin_analytics_income/depfin_analytics_income';
import mediaInfographic from '../components/media-infographic/mediaInfographic';
import mediaEvents from '../components/mediaEvents/mediaEvents';
import mediaSM from '../components/mediaSmFin/mediaSM';
import pressReleases from '../components/press-releases/pressReleases';
import depfinAnalyticsExpenses from '../components/depfin-analytics-expenses/depfinAnalyticsExpenses';
import depfinAnalyticsGP from '../components/depfin-analytics-gp/depfinAnalyticsGP';
import teaserCard from '../blocks/teaser-card/teaserCard';
import footer from '../components/footer/footer';
import pollsTask from '../components/polls-task/pollsTask';

$(() => {
	  // перезагрузка страниц при изменении разрешения
	  $(document).ready(function(){
        
		window.winWidth = $(window).width();
		$(window).resize(function(){
		  if (winWidth !== $(window).width()) {
			location.reload();
		  }
		});
        
        window.addEventListener("orientationchange", function() {
          location.reload();
        }, false);
        
	  });

	  window.basic_budget_figures = basic_budget_figures;
	  basic_budget_figures();
	  aboutBudgetPreparation();
	  window.selectbox = selectbox;
	  selectbox();
	  dragscroll();
	  docCards();
	  mediaMain();
	  documentsform();
	  widgetCard();
	  depfinServices();
	  main();
	  dropdown();
	  analitycWidgethead();
	  pageHeader();
	  question();
	  questions();
	  lkNav();
	  search();
	  window.openReit = openReit;
	  openReit();
	  regions();
	  tabs();
	  news_one();
	  searchForm();
	  window.sources = sources;
	  sources();
	  window.govProgram = govProgram;
	  govProgram();
	  window.analyticsMain = analyticsMain;
	  analyticsMain();
	  legend();
	  budgetCalcPage();
	  budgetCalcApp();
	  newsFilter();
	  range();
	  window.openCon = openCon;
	  openCon();
	  contest();
	  window.openSlider = openSlider;
	  openSlider();
	  mediaMaterials();
	  window.govDebt = govDebt;
	  govDebt();
	  profileEdit();
	  budgetaryPolicy();
	  modal();
	  window.budget_moscow_gov_program = budget_moscow_gov_program;
	  budget_moscow_gov_program();
      window.analitycGraphics = analitycGraphics;
	  analitycGraphics();
	  reset();
	  profile();
	  menu();
	  searchNavbar();
	  header();
	  toppanel();
	  window.tooltips = tooltips;
	  tooltips();
	  aboutBudget();
	  openFile();
	  rangeUi();
	  contestPopup();
	  socialService();
	  window.aip = aip;
	  aip();
	  classifyNew();
	  servicesVMO();
	  window.socialSignificant = socialSignificant;
	  socialSignificant();
	  window.servicesNet = servicesNet;
	  servicesNet();
	  dropTable();
      window.slideArrows = slideArrows;
	  slideArrows();
	  window.budgetForecast = budgetForecast;
	  budgetForecast();
	  window.servicesMoscow = servicesMoscow;
	  servicesMoscow();
	  window.blueDropdown = bluedropdown;
	  bluedropdown();
	  documentsCards();
	  tablesActive();
	  window.mrelations = mrelations;
	  mrelations();
	  window.budgetIncome = budgetIncome;
	  budgetIncome();
	  window.budgetExpenses = budgetExpenses;
	  budgetExpenses();
      window.table = table;
	  table();
	  budgetMoscowOpen();
	  buttonsSet();
	  window.analyticsGovDebt = analyticsGovDebt;
	  analyticsGovDebt();
    window.depfin_analytics_income = depfin_analytics_income;
    depfin_analytics_income();
  	mediaInfographic();
  	mediaEvents();
  	mediaSM();
  	pressReleases();
    window.depfinAnalyticsExpenses = depfinAnalyticsExpenses;
    depfinAnalyticsExpenses();
    window.depfinAnalyticsGP = depfinAnalyticsGP;
    depfinAnalyticsGP();
    teaserCard();
    footer();
    pollsTask();

    window.appLoaded = true;
});
